function X = energyFunction(xyz)
	
    global para;
    
    % - get four projection error
    error_L2L = projectionError('L2L', para.R1, ...
                                       para.T1, ...
                                       para.heatpoint_2D{1}(:,para.point_order), ...
                                       xyz, ...
                                       para.camera, ...
                                       para.center{1}, ...
                                       para.scale{1});
    error_L2R = projectionError('L2R', para.R1, ...
                                       para.T1, ...
                                       para.heatpoint_2D{2}(:,para.point_order), ...
                                       xyz, ...
                                       para.camera, ...
                                       para.center{2}, ...
                                       para.scale{2});
    error_R2L = projectionError('R2L', para.R2, ...
                                       para.T2, ...
                                       para.heatpoint_2D{1}(:,para.point_order), ...
                                       xyz, ...
                                       para.camera, ...
                                       para.center{1}, ...
                                       para.scale{1});
    error_R2R = projectionError('R2R', para.R2, ...
                                       para.T2, ...
                                       para.heatpoint_2D{2}(:,para.point_order), ...
                                       xyz, ...
                                       para.camera, ...
                                       para.center{2}, ...
                                       para.scale{2});
    
    X = error_L2L + error_L2R + error_R2L + error_R2R;
 
end
    